# Leaflet Static Resource Server configuration
lsrs:

  # Server settings
  server:

    # Server context path (API base path)
    context-path: /lsrs

    # Server address to listen on
    host: 0.0.0.0

    # Port to listen on
    port: 8083

  # Database connection settings
  datasource:

    # Database URL
    uri: <provide>

    # Username
    username: <provide>

    # Password
    password: <provide>

    # Instruct Sequelize to log queries
    logging: false

  # Storage settings
  storage:

    # File storage root path
    upload-path: /tmp/storage

    # Maximum age of cached downloaded file
    max-age-in-days: 365

    # Default file permission to be set on upload
    permission: "0744"

    # File type acceptor definitions
    acceptors:

        # Acceptor ID
      - accepted-as: image

        # Name of the acceptor root folder
        group-root-directory: images

        # MIME types to be accepted by this acceptor
        accepted-mime-types:
          - image/*

  # Authorization settings (OAuth 2.0)
  auth:

    # OAuth token issuer name (authorization server address)
    oauth-issuer: <provide>

    # OAuth token audience
    oauth-audience: <provide>

  # Logging settings
  logging:

    #  Log exposure to TinyLogProcessor (TLP) service
    tlp-logging:

      # Enable/disable TLP log exposure
      enabled: false

      # TLP host address
      host: http://localhost:9999/tlp

  # Actuator endpoint settings
  info:

    # Reported application name
    appName: Leaflet Static Resource Server

    # Reported application name abbreviation
    abbreviation: LSRS
