# Leaflet Static Resource Server configuration
lsrs:

  # Server settings
  server:

    # Server address to listen on
    host: 0.0.0.0

    # Port to listen on
    port: 8083

  # Database connection settings
  datasource:

    # Database URL
    uri: <provide>

    # Username
    username: <provide>

    # Password
    password: <provide>

    # Instruct Sequelize to log queries
    logging: false

  # Actuator endpoint settings
  info:

    # Reported application name
    appName: Leaflet Static Resource Server

    # Reported application name abbreviation
    abbreviation: LSRS
