lsrs:
  server:
    context-path: /lsrs
    host: 127.0.0.1
    port: 9998
  datasource:
    uri: "sqlite::memory:"
    username: testuser
    password: testpass1
    logging: false
  storage:
    upload-path: /tmp/storage
    max-age-in-days: 365
    permission: "0744"
    acceptors:
      - accepted-as: image
        group-root-directory: images
        accepted-mime-types:
          - image/*
      - accepted-as: other
        group-root-directory: files
        accepted-mime-types:
          - application/octet-stream
          - application/pdf
  auth:
    oauth-issuer: http://localhost:9999
    oauth-audience: test-lsrs-audience
  logging:
    tlp-logging:
      enabled: false
      host: http://localhost:9999/tlp
  info:
    appName: "[TEST] Leaflet Static Resource Server"
    abbreviation: TEST-LSRS
